services:

  mysql:
    image: mysql:8
    container_name: mysql-container

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  student-app:
    image: haran09/studentexam-app:latest

    container_name: student-app-container

    ports:
      - "4049:4049"

    depends_on:
      - mysql

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/studentdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql-data:
